// App
export const CHANGE_PAGE = 'CHANGE_PAGE';

// PRODUCTS
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';

// CART
export const TOGGLE_SHOW_CART = 'TOGGLE_SHOW_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREMENT_ON_CART = 'INCREMENT_ON_CART';
export const DECREMENT_ON_CART = 'DECREMENT_ON_CART';
export const SET_CART_PROCESSED = 'SET_CART_PROCESSED';
